# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-20 04:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import egghunt.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Egg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequenceNumber', models.IntegerField()),
                ('locationName', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius', models.FloatField()),
                ('textClue', models.TextField(blank=True)),
                ('visits', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('levelJustEnded', models.IntegerField(blank=True, default=None, null=True)),
                ('finalEnd', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=egghunt.models.random_filename)),
                ('egg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egghunt.Egg')),
            ],
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ipAddress', models.CharField(max_length=100)),
                ('publicationDate', models.DateTimeField(verbose_name='Entry time')),
                ('level', models.IntegerField(default=1)),
            ],
        ),
    ]
